/*
 * generated by Xtext
 */
package org.xtext.anomaly.report.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReportUiModule extends org.xtext.anomaly.report.ui.AbstractReportUiModule {
	public ReportUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
