/*
* generated by Xtext
*/
package org.xtext.example.security.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.security.services.SecurityGrammarAccess;

public class SecurityParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SecurityGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.security.parser.antlr.internal.InternalSecurityParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.security.parser.antlr.internal.InternalSecurityParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Security";
	}
	
	public SecurityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SecurityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
