/**
 * generated by Xtext
 */
package org.xtext.anomaly.report.validation;

import org.xtext.anomaly.report.validation.AbstractReportValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ReportValidator extends AbstractReportValidator {
}
