/*
 * generated by Xtext
 */
package org.xtext.example.security;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SecurityRuntimeModule extends org.xtext.example.security.AbstractSecurityRuntimeModule {

}
