/*
* generated by Xtext
*/
package org.xtext.example.security;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SecurityStandaloneSetup extends SecurityStandaloneSetupGenerated{

	public static void doSetup() {
		new SecurityStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

