/*
* generated by Xtext
*/
package org.xtext.anomaly.report;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ReportUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.anomaly.report.ui.internal.ReportActivator.getInstance().getInjector("org.xtext.anomaly.report.Report");
	}
	
}
