/**
 * generated by Xtext
 */
package org.xtext.example.security.validation;

import org.xtext.example.security.validation.AbstractSecurityValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SecurityValidator extends AbstractSecurityValidator {
}
