/*
 * generated by Xtext
 */
package org.xtext.example.security.ui.contentassist

import org.xtext.example.security.ui.contentassist.AbstractSecurityProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SecurityProposalProvider extends AbstractSecurityProposalProvider {
}
