/*
* generated by Xtext
*/
package org.xtext.anomaly.report;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ReportStandaloneSetup extends ReportStandaloneSetupGenerated{

	public static void doSetup() {
		new ReportStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

