/*
 * generated by Xtext
 */
package org.xtext.anomaly.report;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReportRuntimeModule extends org.xtext.anomaly.report.AbstractReportRuntimeModule {

}
