/**
 * generated by Xtext
 */
package org.xtext.anomaly.report.ui.contentassist;

import org.xtext.anomaly.report.ui.contentassist.AbstractReportProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ReportProposalProvider extends AbstractReportProposalProvider {
}
