/*
 * generated by Xtext
 */
package org.xtext.example.security.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SecurityUiModule extends org.xtext.example.security.ui.AbstractSecurityUiModule {
	public SecurityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
