/*
* generated by Xtext
*/
package org.xtext.example.security;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SecurityUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.security.ui.internal.SecurityActivator.getInstance().getInjector("org.xtext.example.security.Security");
	}
	
}
