<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="websecurity">
  <eClassifiers xsi:type="ecore:EClass" name="WebApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aResources" upperBound="-1"
        eType="#//ActiveResource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" upperBound="-1"
        eType="#//Subject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//Request" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="use" upperBound="-1" eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="1"
        upperBound="-1" eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiesAs" eType="#//Subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//Subject"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Subject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPRequest" eSuperTypes="#//Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//HttpMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="#//Resource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" upperBound="-1"
        eType="#//Request" eOpposite="#//Request/subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodRequest" eSuperTypes="#//Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" lowerBound="1"
        upperBound="-1" eType="#//Subject" eOpposite="#//Subject/request"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" lowerBound="1" eType="#//RequestKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequestKind">
    <eLiterals name="Allow"/>
    <eLiterals name="Deny" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthenticatedRole" eSuperTypes="#//Role"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleTransition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRole" lowerBound="1"
        eType="#//Role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRole" lowerBound="1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyHttpMethod" eSuperTypes="#//HttpMethod"/>
</ecore:EPackage>
