/*
* generated by Xtext
*/
package org.xtext.anomaly.report.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.anomaly.report.services.ReportGrammarAccess;

public class ReportParser extends AbstractContentAssistParser {
	
	@Inject
	private ReportGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.anomaly.report.ui.contentassist.antlr.internal.InternalReportParser createParser() {
		org.xtext.anomaly.report.ui.contentassist.antlr.internal.InternalReportParser result = new org.xtext.anomaly.report.ui.contentassist.antlr.internal.InternalReportParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAnomalyAccess().getGroup(), "rule__Anomaly__Group__0");
					put(grammarAccess.getModelAccess().getAnomaliesAssignment(), "rule__Model__AnomaliesAssignment");
					put(grammarAccess.getAnomalyAccess().getNameAssignment_1(), "rule__Anomaly__NameAssignment_1");
					put(grammarAccess.getAnomalyAccess().getDescrAssignment_3(), "rule__Anomaly__DescrAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.anomaly.report.ui.contentassist.antlr.internal.InternalReportParser typedParser = (org.xtext.anomaly.report.ui.contentassist.antlr.internal.InternalReportParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ReportGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReportGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
