<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="servletSecurity" nsURI="http://www.xtext.org/servletSecurity/ServletSecurity"
    nsPrefix="servletSecurity">
  <eClassifiers xsi:type="ecore:EClass" name="Security">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" upperBound="-1" eType="#//SecurityRole"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//SecurityConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleName" eType="#//RoleName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" upperBound="-1"
        eType="#//DisplayName" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webResourceCollection"
        upperBound="-1" eType="#//WebResourceCollection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authConstraint" eType="#//AuthConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userDataConstraint" eType="#//UserDataConstraint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Identifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//SourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceType">
    <eLiterals name="XML" literal="XML"/>
    <eLiterals name="CODE" value="1" literal="CODE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WebResourceCollection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="webResourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="urlPattern" upperBound="-1"
        eType="#//UrlPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="httpMethod" upperBound="-1"
        eType="#//HttpMethod" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Identifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UrlPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omission" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AuthConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleNameTxt" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleName" unique="false"
        upperBound="-1" eType="#//RoleName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Identifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserDataConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transportGuarantee" eType="#//TransportGuarantee"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="#//Identifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransportGuarantee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restriction" eType="#//RestrictionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RestrictionType">
    <eLiterals name="NONE" literal="NONE"/>
    <eLiterals name="INTEGRAL" value="1" literal="INTEGRAL"/>
    <eLiterals name="CONFIDENTIAL" value="2" literal="CONFIDENTIAL"/>
  </eClassifiers>
</ecore:EPackage>
